nmap <F5> :call A()<CR>
func A()
	exec "wa"
	exec "!g++ % -o %< -Wall -std=c++11 && %<"
endfunc

set autoindent
set cindent
set tabstop=4
set shiftwidth=4

set nu
set ruler
set cursorline

syntax on
colorscheme torte

nmap <F9> :call C()<CR>
func C()
	exec "wa"
	exec "!g++ % -o %< -Wall -std=c++11"
endfunc

nmap <C-F9> :!%<<CR>
